// DreamValley compatibility entry point for Twilight Axis' TAT character
// builder. The imported implementation remains in its original namespace so
// upstream TAT updates can be compared and applied without losing attribution.

#include "tat_compat.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\tat_defines.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\_defines\tat_defines_items.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\_defines\tat_defines_skills.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\_defines\tat_defines_stats.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\_defines\tat_defines_traits.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\_defines\tat_defines_directions.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\core\tat_slot.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\core\tat_build.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\core\tat_bans.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\domains\tat_items.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\domains\tat_party_leader.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\domains\tat_directions.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\domains\tat_skills.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\domains\tat_stats.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\domains\tat_traits.dm"
#include "..\..\modular_twilight_axis\code\datums\tat_system\core\tat_ui.dm"
#include "..\..\modular_twilight_axis\code\modules\jobs\job_types\roguetown\tat_build\tat_class.dm"
#include "tat_integration.dm"
#include "alt_form_trait.dm"
#include "tat_quirks.dm"
#include "opposites.dm"
