/datum/foreign_realm/viamedulla
	id = REALM_VIAMEDULLA
	name = "Via Medulla"
	roll_weight = TRADE_REALM_WEIGHT_NEIGHBOR
	demanded_categories = list(NAVIGATOR_BUCKET_WEAPONS, NAVIGATOR_BUCKET_ARMOR_HEAVY, NAVIGATOR_BUCKET_GARMENT_FINELUX, NAVIGATOR_BUCKET_VALUABLES_CRAFTED, NAVIGATOR_BUCKET_VALUABLES_LOOTED, NAVIGATOR_BUCKET_CARVED, NAVIGATOR_BUCKET_TROPHIES, NAVIGATOR_BUCKET_INSTRUMENTS, NAVIGATOR_BUCKET_MISCELLANEOUS)
	ship_name_words = list(
		"Aurelia", "Mirella", "Esperanza", "Fortuna", "Vittoria",
		"Stella", "Corona", "Leone", "Tormenta", "Onore",
		"Armada", "Caravelle", "Sirena", "Falco", "Orso",
	)
	captain_first_names = list(
		"Rodrigo", "Esteban", "Lorenzo", "Diego", "Matteo",
		"Cesare", "Alvaro", "Hernando", "Salvatore", "Vincenzo",
		"Isabela", "Catalina", "Bianca", "Elena", "Lucrezia",
	)
	captain_last_names = list(
		"Zaragoza", "del Mar", "Velasquez", "Aldobrandi", "Cortes",
		"di Montecarina", "de Navarno", "Vellano", "Castellanos", "Lazaretto",
	)
	ship_types = list(
		list("name" = "Caravel", "tonnage" = 70, "weight" = 25),
		list("name" = "Galleon", "tonnage" = 200, "weight" = 35),
		list("name" = "Carrack", "tonnage" = 400, "weight" = 25),
		list("name" = "Armada Galleon", "tonnage" = 700, "weight" = 15),
	)
	name_prefixes = list(
		list("text" = "Don ", "chance" = 5, "requires_proper_name" = FALSE),
		list("text" = "Santa ", "chance" = 10),
	)
	city_tags = list(
		"Gran Zafiro", "Porto del Re", "Portosegreto", "San Vellano",
		"Santa Mirella", "Marenova", "Velasca", "Portavigna",
		"San Rodrigo", "Santa Aurelia", "Puerto Leon", "Miralago",
		"Montejaral", "Alcazora",
	)
	city_tag_chance = 35
	cultural_goods = list()
	bulk_supply_pool_base = list(
		list("good" = TRADE_GOOD_LEMON, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_TANGERINE, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_SALT, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_DEEP_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_FISH_FILET, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_DRIED_FISH, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_LIME, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_GARLICK, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_TOMATO, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_FAIR),
		list("good" = TRADE_GOOD_EGGPLANT, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_TOPER, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DEEP_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_GEMERALD, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DEEP_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_SAFFIRA, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DEEP_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_BLORTZ, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_DORPEL, "qty_min" = BULK_QTY_SMALL_MIN, "qty_max" = BULK_QTY_SMALL_MAX, "price_mod" = BULK_PRICE_DISCOUNT, "always" = TRUE),
		list("good" = TRADE_GOOD_JADE, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DEEP_DISCOUNT),
		list("good" = TRADE_GOOD_OPAL, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_ONYXA, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DEEP_DISCOUNT),
		list("good" = TRADE_GOOD_CERULITE, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_HEARTSTONE, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_AMBER, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DEEP_DISCOUNT),
		list("good" = TRADE_GOOD_ROSESTONE, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_CINNABAR, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_DISCOUNT),
		list("good" = TRADE_GOOD_GOLD_ORE, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_FAIR),
	)
	bulk_demand_pool_base = list(
		list("good" = TRADE_GOOD_IRON_INGOT, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_PREMIUM, "always" = TRUE),
		list("good" = TRADE_GOOD_STEEL_INGOT, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_EAGER_PREMIUM, "always" = TRUE),
		list("good" = TRADE_GOOD_WOOD, "qty_min" = BULK_QTY_HUGE_MIN, "qty_max" = BULK_QTY_HUGE_MAX, "price_mod" = BULK_PRICE_PREMIUM, "always" = TRUE),
		list("good" = TRADE_GOOD_CLOTH, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_PREMIUM, "always" = TRUE),
		list("good" = TRADE_GOOD_FUR, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_EAGER_PREMIUM),
		list("good" = TRADE_GOOD_COAL, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_PREMIUM),
		list("good" = TRADE_GOOD_HIDE, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_PREMIUM),
		list("good" = TRADE_GOOD_CURED_LEATHER, "qty_min" = BULK_QTY_LARGE_MIN, "qty_max" = BULK_QTY_LARGE_MAX, "price_mod" = BULK_PRICE_PREMIUM),
		list("good" = TRADE_GOOD_FIBERS, "qty_min" = BULK_QTY_HUGE_MIN, "qty_max" = BULK_QTY_HUGE_MAX, "price_mod" = BULK_PRICE_FAIR),
		list("good" = TRADE_GOOD_GOLD_INGOT, "qty_min" = BULK_QTY_TINY_MIN, "qty_max" = BULK_QTY_TINY_MAX, "price_mod" = BULK_PRICE_EAGER_PREMIUM),
		list("good" = TRADE_GOOD_PAPER, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_PREMIUM),
		list("good" = TRADE_GOOD_APPLE, "qty_min" = BULK_QTY_SMALL_MIN, "qty_max" = BULK_QTY_SMALL_MAX, "price_mod" = BULK_PRICE_FAIR),
		list("good" = TRADE_GOOD_BLACKBERRY, "qty_min" = BULK_QTY_SMALL_MIN, "qty_max" = BULK_QTY_SMALL_MAX, "price_mod" = BULK_PRICE_PREMIUM),
		list("good" = TRADE_GOOD_GRAIN, "qty_min" = BULK_QTY_HUGE_MIN, "qty_max" = BULK_QTY_HUGE_MAX, "price_mod" = BULK_PRICE_STAPLE_DESPERATE, "always" = TRUE),
		list("good" = TRADE_GOOD_SILVER_INGOT, "qty_min" = BULK_QTY_SMALL_MIN, "qty_max" = BULK_QTY_SMALL_MAX, "price_mod" = BULK_PRICE_EAGER_PREMIUM, "always" = TRUE),
		list("good" = TRADE_GOOD_FAT, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_FAIR),
		list("good" = TRADE_GOOD_POPPY, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_PREMIUM),
		list("good" = TRADE_GOOD_CARROT, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_FAIR),
		list("good" = TRADE_GOOD_COFFEE, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_EAGER_PREMIUM),
		list("good" = TRADE_GOOD_PEAR, "qty_min" = BULK_QTY_SMALL_MIN, "qty_max" = BULK_QTY_SMALL_MAX, "price_mod" = BULK_PRICE_PREMIUM),
		list("good" = TRADE_GOOD_BUTTER, "qty_min" = BULK_QTY_MEDIUM_MIN, "qty_max" = BULK_QTY_MEDIUM_MAX, "price_mod" = BULK_PRICE_STAPLE_PREMIUM),
	)
	victualling_fresh_pool = list(
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/tomatoplate, "qty_min" = VICTUALLING_QTY_MEDIUM_MIN, "qty_max" = VICTUALLING_QTY_MEDIUM_MAX, "price" = VICTUALLING_PRICE_FISH),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/meattomatoplate, "qty_min" = VICTUALLING_QTY_SMALL_MIN, "qty_max" = VICTUALLING_QTY_SMALL_MAX, "price" = VICTUALLING_PRICE_LUXURY),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/fishtomatoplate, "qty_min" = VICTUALLING_QTY_SMALL_MIN, "qty_max" = VICTUALLING_QTY_SMALL_MAX, "price" = VICTUALLING_PRICE_LUXURY),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/pie/cooked/crab, "qty_min" = VICTUALLING_QTY_SMALL_MIN, "qty_max" = VICTUALLING_QTY_SMALL_MAX, "price" = VICTUALLING_PRICE_LUXURY),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/preserved/eggplantstuffedcheese, "qty_min" = VICTUALLING_QTY_SMALL_MIN, "qty_max" = VICTUALLING_QTY_SMALL_MAX, "price" = VICTUALLING_PRICE_FISH),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/ccake, "qty_min" = VICTUALLING_QTY_SMALL_MIN, "qty_max" = VICTUALLING_QTY_SMALL_MAX, "price" = VICTUALLING_PRICE_LUXURY),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/hcake, "qty_min" = VICTUALLING_QTY_MEDIUM_MIN, "qty_max" = VICTUALLING_QTY_MEDIUM_MAX, "price" = VICTUALLING_PRICE_LUXURY),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/menthacake, "qty_min" = VICTUALLING_QTY_MEDIUM_MIN, "qty_max" = VICTUALLING_QTY_MEDIUM_MAX, "price" = VICTUALLING_PRICE_STEAK),
	)
	victualling_preserved_pool = list(
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/crackerscooked, "qty_min" = VICTUALLING_QTY_HUGE_MIN, "qty_max" = VICTUALLING_QTY_HUGE_MAX, "price" = VICTUALLING_PRICE_HARDTACK),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/cheesebun, "qty_min" = VICTUALLING_QTY_LARGE_MIN, "qty_max" = VICTUALLING_QTY_LARGE_MAX, "price" = VICTUALLING_PRICE_SIMPLE),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/applebread, "qty_min" = VICTUALLING_QTY_MEDIUM_MIN, "qty_max" = VICTUALLING_QTY_MEDIUM_MAX, "price" = VICTUALLING_PRICE_FISH),
		list("typepath" = /obj/item/reagent_containers/food/snacks/rogue/raisinbread, "qty_min" = VICTUALLING_QTY_MEDIUM_MIN, "qty_max" = VICTUALLING_QTY_MEDIUM_MAX, "price" = VICTUALLING_PRICE_FISH),
	)
	victualling_drinks_pool = list(
		list("recipe" = /datum/brewing_recipe/beer, "keg_mult" = 2),
		list("recipe" = /datum/brewing_recipe/brandy/plum),
		list("recipe" = /datum/brewing_recipe/brandy),
		list("recipe" = /datum/brewing_recipe/rum),
		list("recipe" = /datum/brewing_recipe/whipwine),
		list("recipe" = /datum/brewing_recipe/luxintenebre),
		list("recipe" = /datum/brewing_recipe/voddena),
		list("recipe" = /datum/brewing_recipe/jack_wine),
		list("recipe" = /datum/brewing_recipe/blackberry_wine),
	)
	cultural_stock_pool = list(
		/datum/supply_pack/rogue/gems/coral,
		/datum/supply_pack/rogue/gems/rose,
		/datum/supply_pack/rogue/food/sugar,
		/datum/supply_pack/rogue/food/chocolate,
		/datum/supply_pack/rogue/merc_weapons/etruscanlongsword,
		/datum/supply_pack/rogue/merc_weapons/erapier,
		/datum/supply_pack/rogue/merc_weapons/navaja,
		/datum/supply_pack/rogue/merc_weapons/saildagger,
		/datum/supply_pack/rogue/etrusca/falchion,
		/datum/supply_pack/rogue/etrusca/crossbow,
		/datum/supply_pack/rogue/etrusca/heavy_bolts,
		/datum/supply_pack/rogue/etrusca/pike,
		/datum/supply_pack/rogue/etrusca/etruscan_bascinet,
		/datum/supply_pack/rogue/etrusca/condottieri_kit,
		/datum/supply_pack/rogue/etrusca/vaquero_kit,
		/datum/supply_pack/rogue/etrusca/jamon,
		/datum/supply_pack/rogue/etrusca/coppiette,
		/datum/supply_pack/rogue/etrusca/salami,
		/datum/supply_pack/rogue/etrusca/cheese,
		/datum/supply_pack/rogue/etrusca/vaquero_ring,
		/datum/supply_pack/rogue/lirvas/tabard,
		/datum/supply_pack/rogue/lirvas/pauldrons,
		/datum/supply_pack/rogue/lirvas/gold_gorget,
		/datum/supply_pack/rogue/lirvas/gold_kilt,
		/datum/supply_pack/rogue/lirvas/gold_quarterstaff,
		/datum/supply_pack/rogue/lirvas/sabre,
		/datum/supply_pack/rogue/lirvas/tithebound_kit,
		/datum/supply_pack/rogue/otava/morningstar,
		/datum/supply_pack/rogue/otava/lance,
		/datum/supply_pack/rogue/otava/flamberge,
		/datum/supply_pack/rogue/otava/falchion,
		/datum/supply_pack/rogue/otava/lucerne,
		/datum/supply_pack/rogue/otava/half_plate,
		/datum/supply_pack/rogue/otava/full_plate,
		/datum/supply_pack/rogue/otava/heavy_gambeson,
		/datum/supply_pack/rogue/otava/klappvisier,
		/datum/supply_pack/rogue/otava/gloves,
		/datum/supply_pack/rogue/otava/boots,
		/datum/supply_pack/rogue/otava/trousers,
		/datum/supply_pack/rogue/otava/satchel,
		/datum/supply_pack/rogue/otava/chevalier_kit,
		/datum/supply_pack/rogue/otava/sergent_kit,
		/datum/supply_pack/rogue/otava/cheese,
		/datum/supply_pack/rogue/alcohol/limoncello,
		/datum/supply_pack/rogue/alcohol/winevalorred,
		/datum/supply_pack/rogue/alcohol/winevalorwhite,
		/datum/supply_pack/rogue/alcohol/wineraneshen,
		/datum/supply_pack/rogue/alcohol/beer,
		/datum/supply_pack/rogue/alcohol/rtoper,
	)
	hail_lines = list(
		"Ah, the Marrow Roads shore at last! Por favor, have my tariff men ready - I am not a patient man when the sun is high.",
		"By the Hoard and the Tithe, we have crossed two storms to reach this pier. I trust your purse is as wide as my hold.",
		"Greetings, signore. My wine is the best on the trade road, and my crew has been told not to spit on your stones. See that you give them no reason.",
		"My chaplain has held sermon every sunsdae since we cleared Porto del Re. Knowledge watches over honest weights at this gangway - bear that in mind.",
		"Gran Zafiro sends greetings under the seal of House Zaragoza. My hold sends lemons. Take both with the respect they are owed.",
		"I sailed from the southern isle, signore - Montecarina born, navy trained, no smuggler. Should any Navarno cousin tell you otherwise upon making port, do not believe them.",
		"Open the chain and have a notary at the gangway. I trade in coin, not in promises - the Forbidden's Stripping-preachers have ruined cleaner pursers than yours.",
		"Salve. I have lemons enough to drown your fevers and salt enough to bury your dead - which would you like first?",
		"My cousin sailed this run last spring and was paid in clipped coin. I will be weighing every piece.",
		"A Vaquero of the Montejaral hills rides with us, returning from a contract abroad. No crown here calls him outlaw. My grandfather called him kin. Treat him as the latter and we will have no quarrel.",
		"I carry a Condottieri captain bound for sellsword work abroad. His arms are stowed, his crossbow is oiled, and his pay is none of our concern until we make port.",
		"The crossing was kind. The Factor, I am told, is less so. Let us see if both rumors hold.",
		"A priest aboard swears the figurehead wept blood off the Bleak Coast. I have him locked in the hold. Buy quickly so I may sail before the rest of the crew gets ideas.",
		"My second cousin Federico travels with the cargo. He is - how shall I put this - acquainted with men who can move things quietly and quickly between Porto del Re and your Goldface, when official channels prove inconvenient. His fee is modest. His memory is shorter. Ask for him by name and not by trade, signore.",
		"By the Hoard and the Tithe, Factor, you have kept a faithful ledger. The scales remember.",
		"My grain is short. My gems are not. The free cities send their compliments and their hunger.",
		"Mammon weighs every transaction, friend, and the Rings remember what Mammon weighs. Give honest measure - or do not, and learn the cost in a quieter season.",
		"I am Tithebound. My captain's purse is not mine; it is the Hoard's. Speak prices accordingly.",
		"A coin dropped on the Marrow Roads takes seven years to settle. Yours, here, will be counted in heartbeats. Try to keep up.",
		"You burn coin for warmth in your hearths. We do not. Sell us your grain and you will learn why.",
		"A Tithecaster of the Inner Ring rides with me, weighing souls in coin as her line has done for three generations. For one gold sovereign she will tell you the weight your sins would fetch at the Hoard's scales upon your death. She has not been wrong yet.",
	)
